# Generated by Django 3.1.6 on 2021-03-13 00:29

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('texteditor', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.CharField(default='Codin India', max_length=150)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
